namespace: capi-system

namePrefix: capi-



# Provide customizable hook for make targets.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../config/manager
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: cluster-api
patches:
- path: patch_service_account.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: patch_healthcheck.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: ../../../config/default/manager_image_patch.yaml
- path: ../../../config/default/manager_pull_policy.yaml
