namespace: capi-webhook-system

namePrefix: capi-

#configurations:
#- ../../../config/default/kustomizeconfig.yamlq

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../config/default/namespace.yaml
- ../../../config/crd
- ../../../config/manager
- ../../../config/webhook
- ../../../config/certmanager

labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: cluster-api

patches:
- path: patch_namespace.yaml
  target:
    kind: Namespace
    name: system
    version: v1
- path: patch_service_account.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: clusters.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machinedeployments.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machines.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machinesets.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machinehealthchecks.cluster.x-k8s.io
    version: v1
- path: ../../../config/default/manager_image_patch.yaml
- path: ../../../config/default/manager_pull_policy.yaml
- path: ../../../config/default/manager_webhook_patch.yaml
- path: ../../../config/default/webhookcainjection_patch.yaml

replacements:
  - source:
      fieldPath: .metadata.namespace
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
    targets:
      - fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
        select:
          kind: ValidatingWebhookConfiguration
      - fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
        select:
          kind: MutatingWebhookConfiguration
      - fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
        select:
          kind: CustomResourceDefinition
        reject:
          - name: ipaddressclaims.ipam.cluster.x-k8s.io
          - name: ipaddresses.ipam.cluster.x-k8s.io
          - name: extensionconfigs.runtime.cluster.x-k8s.io
  - source:
      fieldPath: .metadata.name
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
    targets:
      - fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
          index: 1
        select:
          kind: ValidatingWebhookConfiguration
      - fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
          index: 1
        select:
          kind: MutatingWebhookConfiguration
      - fieldPaths:
          - .metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          create: true
          delimiter: /
          index: 1
        select:
          kind: CustomResourceDefinition
        reject:
          - name: ipaddressclaims.ipam.cluster.x-k8s.io
          - name: ipaddresses.ipam.cluster.x-k8s.io
          - name: extensionconfigs.runtime.cluster.x-k8s.io
  - source:
      fieldPath: .metadata.name
      kind: Service
      name: webhook-service
      version: v1
    targets:
      - fieldPaths:
          - .spec.dnsNames.0
          - .spec.dnsNames.1
        options:
          create: true
          delimiter: .
        select:
          group: cert-manager.io
          kind: Certificate
          version: v1
  - source:
      fieldPath: .metadata.namespace
      kind: Service
      name: webhook-service
      version: v1
    targets:
      - fieldPaths:
          - .spec.dnsNames.0
          - .spec.dnsNames.1
        options:
          create: true
          delimiter: .
          index: 1
        select:
          group: cert-manager.io
          kind: Certificate
          version: v1