namespace: capi-webhook-system

namePrefix: capi-


# added here and patched to have capi-webhook-system namespace crd
resources:
- ../../../config/default/namespace.yaml
- ../../../config/crd
- ../../../config/manager
- ../../../config/webhook
- ../../../config/certmanager


# Provide customizable hook for make targets.
# Enable webhook.
# Inject certificate in the webhook definition.

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: CERTIFICATE_NAMESPACE
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref: {}
  name: CERTIFICATE_NAME
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref:
    fieldPath: metadata.namespace
  name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: webhook-service
    version: v1
- fieldref: {}
  name: SERVICE_NAME
  objref:
    kind: Service
    name: webhook-service
    version: v1

configurations:
- ../../../config/default/kustomizeconfig.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: cluster-api
patches:
- path: patch_namespace.yaml
  target:
    kind: Namespace
    name: system
    version: v1
- path: patch_service_account.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: clusters.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machinedeployments.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machines.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machinesets.cluster.x-k8s.io
    version: v1
- path: patch_crd_webhook_namespace.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: machinehealthchecks.cluster.x-k8s.io
    version: v1
- path: ../../../config/default/manager_image_patch.yaml
- path: ../../../config/default/manager_pull_policy.yaml
- path: ../../../config/default/manager_webhook_patch.yaml
- path: ../../../config/default/webhookcainjection_patch.yaml
