name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write # Allow to create a release.

jobs:
  build:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: build image
        run: |
          REGISTRY=gcr.io/spectro-image-public/release TAG=${{env.GITHUB_REF_NAME}} make docker-build
      - name: push image
        run: |
          REGISTRY=gcr.io/spectro-image-public/release TAG=${{env.GITHUB_REF_NAME}} make docker-push
